version: "3"
services:
  app:
    cpus: 4
    mem_limit: 15g
    build:
      context: ../..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces/microns_phase3_nda:cached
    command: bash -c "while sleep 1000; do :; done"
